JobPortal/Controllers/MenuItemsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DAL.Models;
using DAL.Controller;
using JobPortal.Controllers.Common;

namespace JobPortal.Controllers
{
    public class MenuItemsController : BaseController
    {
        public MenuItemsController() : base("MenuItem"){}

        // GET: MenuItems
        public override ActionResult Index()
        {
            base.Index();
            return View(DataController<MenuItem>.GetAll());
        }
        
        //GET: MenuItems By SubmenuId
        public ActionResult GetMenuItemsBySubmenuId()
        {
            int submenuId;
            Int32.TryParse(Request["SubmenuId"], out submenuId);
            var s = from p in DataController<MenuItem>.GetAll().AsEnumerable()
                    where p.SubMenuId == submenuId
                    select new MenuItem { Sl = p.Sl, Name = p.Name };
            return Json(s, JsonRequestBehavior.AllowGet);
        }

        // GET: MenuItems/Details/5
        public override ActionResult Details(int? id)
        {
            base.Details(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = DataController<MenuItem>.GetById(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            return View(menuItem);
        }

        // GET: MenuItems/Create
        public override ActionResult Create()
        {
            base.Create();
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name");
            ViewBag.SubMenuId = new SelectList(DataController<SubMenu>.GetAll(), "Sl", "Name");
            return View("Edit");
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Name,IconClass,Order,MenuId,SubMenuId,ControllerName,ActionName")] MenuItem menuItem)
        {
            base.Create();
            if (ModelState.IsValid)
            {
                DataController<MenuItem>.Insert(menuItem);
                return RedirectToAction("Index");
            }
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", menuItem.MenuId);
            ViewBag.SubMenuId = new SelectList(DataController<SubMenu>.GetAll(), "Sl", "Name", menuItem.SubMenuId);
            return View("Edit",menuItem);
        }

        // GET: MenuItems/Edit/5
        public override ActionResult Edit(int? id)
        {
            base.Edit(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = DataController<MenuItem>.GetById(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", menuItem.MenuId);
            ViewBag.SubMenuId = new SelectList(DataController<SubMenu>.GetAll(), "Sl", "Name", menuItem.SubMenuId);
            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Name,IconClass,Order,MenuId,SubMenuId,ControllerName,ActionName")] MenuItem menuItem)
        {
            base.Edit(menuItem.Sl);
            if (ModelState.IsValid)
            {
                DataController<MenuItem>.Update(menuItem);
                return RedirectToAction("Index");
            }
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", menuItem.MenuId);
            ViewBag.SubMenuId = new SelectList(DataController<SubMenu>.GetAll(), "Sl", "Name", menuItem.SubMenuId);
            return View(menuItem);
        }

        // GET: MenuItems/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    ViewBag.ViewProperty = PageController.GetViewProperty(Enums.ViewPage.Delete, "MenuItem");
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    MenuItem menuItem = DataController<MenuItem>.GetById(id);
        //    if (menuItem == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(menuItem);
        //}

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public override ActionResult Delete(int id)
        {
            MenuItem menuItem = DataController<MenuItem>.GetById(id);
            DataController<MenuItem>.Delete(menuItem);
            return RedirectToAction("Index");
        }
    }
}

JobPortal/Views/MenuItems/Details.cshtml
@model DAL.Models.MenuItem

@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
}
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubMenuId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubMenuId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ControllerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ControllerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IconClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IconClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>
    </dl>
</div>

JobPortal/Views/MenuItems/Edit.cshtml
@using Others.Enum
@using Others.UI
@model DAL.Models.MenuItem

@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
    if (((ViewProperty)ViewBag.ViewProperty).ViewPage.Equals(Enums.ViewPage.Edit))
    {
        @Html.HiddenFor(model => model.Sl)
    }
}

<div class="form-group">
    @Html.LabelFor(model => model.MenuId, "MenuId", htmlAttributes: new { @class = "control-label" })
    @Html.DropDownList("MenuId", null, "Select Menu", htmlAttributes: new { @class = "form-control", @id = "ddl_menu", @name = "ddl_menu", @onchange = "LoadSubMenu();" })
    @Html.ValidationMessageFor(model => model.MenuId, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.SubMenuId, "SubMenuId", htmlAttributes: new { @class = "control-label" })
    @Html.DropDownList("SubMenuId", null, "Select SubMenu", htmlAttributes: new { @class = "form-control", @id = "ddl_subMenu", @name = "ddl_subMenu"})
    @Html.ValidationMessageFor(model => model.SubMenuId, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.Name) } })
    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.ControllerName, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.ControllerName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.ControllerName, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.ActionName, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.ActionName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.ActionName, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.IconClass, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.IconClass, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.IconClass) } })
    @Html.ValidationMessageFor(model => model.IconClass, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.Order) } })
    @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
</div>

@section scripts
{
    <script>
        function LoadSubMenu() {
            $.ajax({
                url: '/Page/GetJsonSubMenusByMenuId',
                method: 'POST',
                data: {
                    MenuId: $('#ddl_menu').val(),
                },
                cache: false,
                error: function () {
                    alert("An error occoured!");
                },
                success: function (response) {
                    $('#ddl_subMenu').empty();
                    $('#ddl_subMenu').append($('<option>', {
                        value: '',
                        text: 'Select SubMenu'
                    }));
                    for (var i = 0; i < response.length; i++) {
                        var opt = new Option(response[i].Name, response[i].Sl);
                        $('#ddl_subMenu').append(opt);
                    }
                }
            });
        };
    </script>
}

JobPortal/Views/MenuItems/Index.cshtml
@model IEnumerable<DAL.Models.MenuItem>
@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
    int rowNo = 0;
}
<table id="myTable" class="table table-striped dt-responsive" width=100%>
    <thead>
        <tr>
            <th>SL</th>
            <th>Action</th>
            <th>
                @Html.DisplayNameFor(model => model.MenuId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubMenuId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IconClass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ControllerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActionName)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(rowNo += 1)
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-expanded="false">Options <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Details", "Details", new { id = item.Sl })</li>
                            <li>@Html.ActionLink("Edit", "Edit", new { id = item.Sl })</li>
                            <li><a id="deleteItem" href="#" class="deleteItem" data-target="#modal-delete" data-toggle="modal" data-path="@Url.Action("Delete", "MenuItems", new {id = @item.Sl})">Delete</a></li>
                            @*<li>@Html.ActionLink("Delete", "#", new {id = item.Sl}, new {data_toggle = "modal", data_target = "#modal-default"})</li>*@
                        </ul>
                    </div>
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.MenuId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubMenuId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IconClass)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ControllerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActionName)
                </td>
            </tr>
        }
    </tbody>
</table>


@section content
{
    @Styles.Render("~/Content/dataTable")
}
@section scripts
{
    @Scripts.Render("~/bundles/dataTable")
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                'processing': true
            });
        });
    </script>
    <script>
        var path_to_delete;

        $(".deleteItem").click(function (e) {
            path_to_delete = $(this).data('path');
            $('#deleteForm').attr('action', path_to_delete);
        });
        $('#btnContinueDelete').click(function () {
            document.getElementById("form1").submit();
            window.location = path_to_delete;
        });
    </script>
}