JobPortal/Controllers/SubMenusController.cs
using System.Net;
using System.Web.Mvc;
using DAL.Models;
using DAL.Controller;
using JobPortal.Controllers.Common;

namespace JobPortal.Controllers
{
    public class SubMenusController : BaseController
    {
        public SubMenusController() : base("SubMenu"){}
        
        // GET: SubMenus
        public override ActionResult Index()
        {
            base.Index();
            return View(DataController<SubMenu>.GetAll());
        }

        // GET: SubMenus/Details/5
        public override ActionResult Details(int? id)
        {
            base.Details(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubMenu subMenu = DataController<SubMenu>.GetById(id);
            if (subMenu == null)
            {
                return HttpNotFound();
            }
            return View(subMenu);
        }

        // GET: SubMenus/Create
        public override ActionResult Create()
        {
            base.Create();
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name");
            return View("Edit");
        }

        // POST: SubMenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Name,IconClass,Order,MenuId")] SubMenu subMenu)
        {
            base.Create();
            if (ModelState.IsValid)
            {
                DataController<SubMenu>.Insert(subMenu);
                return RedirectToAction("Index");
            }

            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", subMenu.MenuId);
            return View("Edit",subMenu);
        }

        // GET: SubMenus/Edit/5
        public override ActionResult Edit(int? id)
        {
            base.Edit(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubMenu subMenu = DataController<SubMenu>.GetById(id);
            if (subMenu == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", subMenu.MenuId);
            return View(subMenu);
        }

        // POST: SubMenus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Name,IconClass,Order,MenuId")] SubMenu subMenu)
        {
            base.Edit(subMenu.Sl);
            if (ModelState.IsValid)
            {
                DataController<SubMenu>.Update(subMenu);
                return RedirectToAction("Index");
            }
            ViewBag.MenuId = new SelectList(DataController<Menu>.GetAll(), "Sl", "Name", subMenu.MenuId);
            return View(subMenu);
        }

        // POST: SubMenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public override ActionResult Delete(int id)
        {
            SubMenu subMenu = DataController<SubMenu>.GetById(id);
            DataController<SubMenu>.Delete(subMenu);
            return RedirectToAction("Index");
        }
    }
}

JobPortal/Views/SubMenus/Details.cshtml
@model DAL.Models.SubMenu

@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IconClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IconClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>
</div>

JobPortal/Views/SubMenus/Edit.cshtml
@using Others.Enum
@using Others.UI
@model DAL.Models.SubMenu

@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
    if (((ViewProperty)ViewBag.ViewProperty).ViewPage.Equals(Enums.ViewPage.Edit))
    {
        @Html.HiddenFor(model => model.Sl)
    }
}
<div class="form-group">
    @Html.LabelFor(model => model.MenuId, htmlAttributes: new { @class = "control-label" })
    @Html.DropDownList("MenuId",null, "Select Menu", htmlAttributes: new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.MenuId, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.Name) } })
    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.IconClass, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.IconClass, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.IconClass) } })
    @Html.ValidationMessageFor(model => model.IconClass, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label" })
    @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control", @placeholder = @Html.DisplayNameFor(n => n.Order) } })
    @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
</div>

JobPortal/Views/SubMenus/Index.cshtml
@model IEnumerable<DAL.Models.SubMenu>
@{
    Layout = "~/Views/Shared/PartialView/_NestedLayout.cshtml";
    int rowNo = 0;
}
<table id="myTable" class="table table-striped dt-responsive" width=100%>
    <thead>
        <tr>
            <th>SL</th>
            <th>Action</th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IconClass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MenuId)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(rowNo += 1)
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-expanded="false">Options <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Details", "Details", new { id = item.Sl })</li>
                            <li>@Html.ActionLink("Edit", "Edit", new { id = item.Sl })</li>
                            <li><a id="deleteItem" href="#" class="deleteItem" data-target="#modal-delete" data-toggle="modal" data-path="@Url.Action("Delete", "SubMenus", new {id = @item.Sl})">Delete</a></li>
                            @*<li>@Html.ActionLink("Delete", "#", new {id = item.Sl}, new {data_toggle = "modal", data_target = "#modal-default"})</li>*@
                        </ul>
                    </div>
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IconClass)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Menu.Name)
                </td>
            </tr>
        }
    </tbody>
</table>


@section content
{
    @Styles.Render("~/Content/dataTable")
}
@section scripts
{
    @Scripts.Render("~/bundles/dataTable")
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                'processing': true
            });
        });
    </script>
    <script>
        var path_to_delete;

        $(".deleteItem").click(function (e) {
            path_to_delete = $(this).data('path');
            $('#deleteForm').attr('action', path_to_delete);
        });
        $('#btnContinueDelete').click(function () {
            document.getElementById("form1").submit();
            window.location = path_to_delete;
        });
    </script>
}